name: partner
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  firebase_analytics: ^8.3.1
  firebase_auth: ^3.1.0
  firebase_core: ^1.6.0
  firebase_messaging: ^10.0.6
  fluttertoast: ^8.0.8
  get: 4.3.8
  location: ^4.3.0
  velocity_x: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
